card(class) create, delete 구현 완료
InoFlexin/meta-class pull request #34
Opened 2021-08-09 15:44 UTC by kebin0613

# 구현한 기능
- LandingPage의 card 추가, 제거 구현 및 서버와 테스트 완료

# 사용한 라이브러리
- axios

# 대략적인 코드 설명
- (1) LandingPage의 axios.post 부분 수정 하였습니다.
- (2) LandingPage의 card 삭제 handleDelete 미완성부분을 완성 하였습니다.
- (3) LandingPage의 card map 오류 수정, class 생성 모달 부분 수정 하였습니다.
- (4) LandingPage의 axios.get 부분 수정, class생성 모달 부분 재수정 하였습니다.
- (5) LandingPage의 class 생성 모달의 이미지 업로드 부분 추가 하였습니다.(기능은 보류)

2021-08-09 16:15 UTC, KCH6937 reviewed
만드시느라 고생하셨습니다. 
PR 반영시 테스트 해보도록 하겠습니다.

2021-08-09 16:15 UTC, KCH6937 commented on react/meta-class-client/src/components/LandingPage/LandingPage.js
> -  });
오.. 이런 방식으로 생성이 되는군요
공부가 되네요

2021-08-09 16:17 UTC, kebin0613 commented on react/meta-class-client/src/components/LandingPage/LandingPage.js
> -  });
그렇죠,, NDY 팀장이 괜히 이렇게 하라고 한게 아니죠ㅎㅎ
공부가 되셨다니 다행입니다.

2021-08-09 22:51 UTC, devdynam0507 commented on react/meta-class-client/src/components/LandingPage/LandingPage.js
> +          accessToken: localStorage.getItem("accessToken"),
이부분에서 헤더에 accessToken으로 넣어주는것이 아닌 X-AUTH-TOKEN 으로 넣어주셔야합니다

2021-08-10 05:16 UTC, kebin0613 commented on react/meta-class-client/src/components/LandingPage/LandingPage.js
> +          accessToken: localStorage.getItem("accessToken"),
앗,, 알겠습니다,, 
오늘 수업끝나고 수정할께요

2021-08-11 12:45 UTC, devdynam0507 requested changes

2021-08-11 12:45 UTC, devdynam0507 commented on react/meta-class-client/src/components/LandingPage/LandingPage.js
>            xAuthToken: localStorage.getItem("xAuthToken"),
xAuthToken -> X-AUTH-TOKEN

2021-08-11 13:47 UTC, merged