Frontend - Redirect, Image upload 추가, style 변경
InoFlexin/meta-class pull request #40
Opened 2021-08-17 19:21 UTC by kebin0613

# 구현한 기능
- Redirect
- Image upload
- css 수정

# 사용한 라이브러리
- axios

# 대략적인 코드 설명
<로그인 했을때>
-  Landing Page로 redirect
- NavBar의 'Login'이 'Logout'으로 변경 (조건부렌더링)

<로그아웃 했을때>
-  LoginPage로 redirect
- NavBar의 'Logout'이 "Login"으로 변경 (조건부렌더링)

<css 수정>
- 불완전했던 NavBar, Login, RegisterPage css수정

2021-08-18 16:27 UTC, devdynam0507 requested changes

2021-08-18 16:27 UTC, devdynam0507 commented on react/meta-class-client/src/components/NavBar/NavBar.js
> +          <a href="/" className="logo">
이부분 문제되지않나요 ?
React route가 아닌 일반 href면 whitelabel이 뜰 가능성이있습니다

2021-08-19 11:29 UTC, kebin0613 commented on react/meta-class-client/src/components/NavBar/NavBar.js
> +          <a href="/" className="logo">
앗!! 그렇네요,, 이런 실수를,,, 
빠른 시일내에 수정하겠습니다.

2021-08-21 14:45 UTC, kebin0613 commented
@devdynam0507  
수정완료 했습니다.

2021-08-21 15:07 UTC, merged